# =============================================================================
# Commitlint Configuration
# =============================================================================
# Enforces conventional commit message format.
# Reference: https://commitlint.js.org/
# =============================================================================

extends:
  - "@commitlint/config-conventional"

rules:
  # --- Type ---
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - chore
      - ci
      - test
      - refactor
      - perf
  type-case:
    - 2
    - always
    - lower-case
  type-empty:
    - 2
    - never

  # --- Scope ---
  scope-case:
    - 2
    - always
    - lower-case

  # --- Subject ---
  subject-case:
    - 2
    - always
    - lower-case
  subject-empty:
    - 2
    - never
  subject-full-stop:
    - 2
    - never
    - "."

  # --- Header ---
  header-max-length:
    - 2
    - always
    - 100

  # --- Body ---
  body-max-line-length:
    - 1
    - always
    - 200
  body-leading-blank:
    - 2
    - always

  # --- Footer ---
  footer-leading-blank:
    - 2
    - always

helpUrl: "https://www.conventionalcommits.org/"
